name: geneticNN_ROCm
channels:
  - defaults
dependencies:
  - pip=23.3
  - python=3.11.5
  - setuptools=68.0.0
  - pip:
    - --requirement requirements.txt
    - --requirement requirements-rocm.txt



